### ISSUE TITLE
Trying to run iOS/Android results in babel/polyfill error

### ISSUE THREAD

**Issue by dgsunesen** [sesteva/react-shared-components#5]
I have installed all necessary stuff to get it running, web works fine, but I cannot get neither iOS nor Android to run. I keep getting the following error:

```
/Users/Dan/Downloads/react-shared-components-master/node_modules/babel-core/lib/polyfill.js:8
  throw new Error("only one instance of babel/polyfill is allowed");
  ^

Error: only one instance of babel/polyfill is allowed
    at Object.<anonymous> (/Users/Dan/Downloads/react-shared-components-master/node_modules/babel-core/lib/polyfill.js:8:9)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/Dan/Downloads/react-shared-components-master/node_modules/babel-core/lib/api/register/node-polyfill.js:8:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

**Comment by sesteva** [comment]
Hi. This version has some conflicts with the polyfills and Babel. I have an updated one. I'll push it as soon as I can.
